#!/bin/bash -e

exec 2>&1

func_check_ip_count() {
    local ip_count
    ip_count=$(hostname -I | sed 's/ /\n/g' | grep -cv '^$')
    echo "$ip_count"
}

origin_ip_count=$(func_check_ip_count)
while true; do
    if [ "$(func_check_ip_count)" -gt "$origin_ip_count" ]; then
        harborctl start
    fi

    if [ "$(func_check_ip_count)" -lt "$origin_ip_count" ]; then
        harborctl stop
    fi
    sleep 1
done
