#!/bin/bash
set -xe

exec 2>&1

container_name="keepalived"
script_dir=$(
    cd "$(dirname "${BASH_SOURCE[0]}")"
    pwd
)
keepalived_conf_dir="${script_dir}/keepalived"
keepalived_conf_template_file="${keepalived_conf_dir}/keepalived-${KEEPALIVED_ROLE}.template"
keepalived_conf_file="${keepalived_conf_dir}/keepalived.conf"

# prepare keepalived
if [ ! -d "/sys/module/ip_vs" ]; then
    echo "loading ip_vs module"
    modprobe ip_vs || exit $?
fi

func_status() {
    if [ "$(docker ps -qf name=$container_name)" ]; then
        echo "keepalived is running..."
        return 0
    else
        echo "keepalived is not running!"
        return 1
    fi
}

func_start() {
    echo "generating $keepalived_conf_file"
    if [ ! -f "$keepalived_conf_file" ]; then
        touch "$keepalived_conf_file"
    fi
    envsubst <"$keepalived_conf_template_file" >"$keepalived_conf_file" || exit $?
    echo "running keepalived container"
    docker run -d --rm \
        --name=$container_name \
        --cap-add=NET_ADMIN \
        --cap-add=NET_BROADCAST \
        --cap-add=NET_RAW \
        --net=host \
        --volume "$keepalived_conf_file":/container/service/keepalived/assets/keepalived.conf \
        --volume "$keepalived_conf_dir"/harbor_healthz:/container/service/keepalived/assets/harbor_healthz \
        osixia/keepalived:2.0.20 --copy-service
}

case "$1" in
    status)
        func_status
        ;;
    start)
        func_start
        ;;
    *)
        echo "Usage: keepalivedctl status | start"
        ;;
esac
