#!/bin/bash
set -xe

exec 2>&1

container_name="keepalived"
script_dir=$(
    cd "$(dirname "${BASH_SOURCE[0]}")"
    pwd
)

# prepare keepalived
if [ ! -d "/sys/module/ip_vs" ]; then
    echo "loading ip_vs module"
    modprobe ip_vs || exit $?
fi

func_status() {
    if [ "$(docker ps -qf name=$container_name)" ]; then
        echo "keepalived is running..."
        return 0
    else
        echo "keepalived is not running!"
        return 1
    fi
}

func_start() {
    echo "generating $keepalived_conf_file"
    keepalived_conf_template_file="${script_dir}/keepalived/keepalived-${KEEPALIVED_ROLE}.template"
    keepalived_conf_dir="/etc/keepalived"
    keepalived_conf_file="${keepalived_conf_dir}/keepalived.conf"
    if [ ! -d $keepalived_conf_dir ]; then
        mkdir -p $keepalived_conf_dir
    fi
    if [ ! -f $keepalived_conf_file ]; then
        touch $keepalived_conf_file
    fi
    envsubst <"$keepalived_conf_template_file" >"$keepalived_conf_file" || exit $?
    cp "${script_dir}"/keepalived/harbor_healthz $keepalived_conf_dir
    docker run -d --rm --name=$container_name --cap-add=NET_ADMIN --cap-add=NET_BROADCAST --cap-add=NET_RAW --net=host --volume /etc/keepalived:/container/service/keepalived/assets osixia/keepalived:2.0.20
}

case "$1" in
    status)
        func_status
        ;;
    start)
        func_start
        ;;
    *)
        echo "Usage: keepalivedctl status | start"
        ;;
esac
