#!/bin/bash

set -xe

exec 2>&1

if [ -z "$HARBOR_VERSION" ]; then
    echo "HARBOR_VERSION is undefined"
    exit 1
fi
if [ -z "$HARBOR_VIP" ]; then
    echo "HARBOR_VIP is undefined"
    exit 1
fi
if [ -z "$CEPH_POOL_NAME" ]; then
    echo "CEPH_POOL_NAME is undefined"
    exit 1
fi
if [ -z "$CEPH_IMAGE_NAME" ]; then
    echo "CEPH_IMAGE_NAME is undefined"
    exit 1
fi
if [ -z "$CEPH_MON_HOST" ]; then
    echo "CEPH_MON_HOST is undefined"
    exit 1
fi
if [ -z "$CEPH_USER" ]; then
    echo "CEPH_USER is undefined"
    exit 1
fi
if [ -z "$CEPH_USER_KEY" ]; then
    echo "CEPH_USER_KEY is undefined"
    exit 1
fi
if [ -z "$KEEPALIVED_ROLE" ]; then
    echo "KEEPALIVED_ROLE is undefined"
    exit 1
fi
if [ -z "$INTERFACE" ]; then
    echo "INTERFACE is undefined"
    exit 1
fi

script_dir=$(
    cd "$(dirname "${BASH_SOURCE[0]}")"
    pwd
)

chown -R root:root "$script_dir"
chmod +x "$script_dir"/keepalivedctl "$script_dir"/harborctl
"$script_dir"/harborctl init

if ! "$script_dir"/keepalivedctl status; then
    "$script_dir"/keepalivedctl start
fi

while true; do
    if ip addr | grep -q "$HARBOR_VIP"; then
        echo "vip is here"
        if ! "$script_dir"/harborctl status; then
            "$script_dir"/harborctl start
        fi
    else
        echo "vip is not here"
        if "$script_dir"/harborctl status; then
            "$script_dir"/harborctl stop
        fi
    fi
    sleep 2
done
