#!/bin/bash
set -xe

# pull latest tag
# docker pull registry.cn-beijing.aliyuncs.com/llaoj/harbor-assistant
# run assistant:
# required by docker-compose
#   -v /var/run/docker.sock:/var/run/docker.sock
# required by modprobe to add kernel module
#   -v /lib/modules:/lib/modules
#   -v /sys:/sys
# required by keepalived
#   --cap-add=NET_ADMIN
#   --cap-add=NET_BROADCAST
#   --cap-add=NET_RAW
# required by rbd
#   -v /dev:/dev
# required by mount
#   -v /run/mount:/run/mount
# docker run \
#     -it --rm \
#     --name harbor-assistant \
#     -e CEPH_MON_HOST='10.206.65.20,10.206.65.21,10.206.65.22' \
#     -e CEPH_USER='admin' \
#     -e CEPH_USER_KEY='AQAflFtjHD12AxAAMvsTCWU59t1Tm0VyytmJuA==' \
#     -e CEPH_IMAGE_SPEC='kubernetes/harbor_data' \
#     -e KEEPALIVED_VIP='10.206.65.111' \
#     -e KEEPALIVED_ROLE='master' \
#     -e INTERFACE='eth0' \
#     --net=host \
#     --pid=host \
#     --privileged \
#     --cap-add=SYS_ADMIN \
#     -v /var/run/docker.sock:/var/run/docker.sock \
#     -v /lib/modules:/lib/modules \
#     -v /sys:/sys \
#     -v /run/mount:/run/mount \
#     -v /dev:/dev \
#     -v /mnt:/mnt \
#     registry.cn-beijing.aliyuncs.com/llaoj/harbor-assistant bash

exec 2>&1

if [ -z "$CEPH_POOL_NAME" ]; then
    echo "CEPH_POOL_NAME is undefined"
    exit 1
fi
if [ -z "$CEPH_IMAGE_NAME" ]; then
    echo "CEPH_IMAGE_NAME is undefined"
    exit 1
fi
if [ -z "$CEPH_MON_HOST" ]; then
    echo "CEPH_MON_HOST is undefined"
    exit 1
fi
if [ -z "$CEPH_USER" ]; then
    echo "CEPH_USER is undefined"
    exit 1
fi
if [ -z "$CEPH_USER_KEY" ]; then
    echo "CEPH_USER_KEY is undefined"
    exit 1
fi
if [ -z "$KEEPALIVED_VIP" ]; then
    echo "KEEPALIVED_VIP is undefined"
    exit 1
fi
if [ -z "$KEEPALIVED_ROLE" ]; then
    echo "KEEPALIVED_ROLE is undefined"
    exit 1
fi

if ! keepalivedctl status; then
    keepalivedctl start
fi

func_has_vip() {
    local ip_list
    ip_list=$(hostname -I | sed 's/ /\n/g' | grep -v '^$')
    if [ "$ip_list" ]; then
        for ip in $ip_list; do
            if [ "$ip" -eq "$KEEPALIVED_VIP" ]; then
                echo "Y"
                return
            fi
        done
    fi
    echo "N"
}

has_vip=$(func_has_vip)
while true; do
    if [ "$has_vip" == "Y" ] && [ "$(func_has_vip)" == "N" ]; then
        echo "vip gone"
        has_vip="N"
        harborctl stop
    fi
    if [ "$has_vip" == "N" ] && [ "$(func_has_vip)" == "Y" ]; then
        echo "vip coming"
        has_vip="Y"
        harborctl start
    fi
    sleep 1
done
