#!/bin/bash

set -xe

exec 2>&1

if [ -z "$HARBOR_VERSION" ]; then
    echo "HARBOR_VERSION is undefined"
    exit 1
fi
if [ -z "$HARBOR_VIP" ]; then
    echo "HARBOR_VIP is undefined"
    exit 1
fi
if [ -z "$CEPH_POOL_NAME" ]; then
    echo "CEPH_POOL_NAME is undefined"
    exit 1
fi
if [ -z "$CEPH_IMAGE_NAME" ]; then
    echo "CEPH_IMAGE_NAME is undefined"
    exit 1
fi
if [ -z "$CEPH_MON_HOST" ]; then
    echo "CEPH_MON_HOST is undefined"
    exit 1
fi
if [ -z "$CEPH_USER" ]; then
    echo "CEPH_USER is undefined"
    exit 1
fi
if [ -z "$CEPH_USER_KEY" ]; then
    echo "CEPH_USER_KEY is undefined"
    exit 1
fi
if [ -z "$KEEPALIVED_ROLE" ]; then
    echo "KEEPALIVED_ROLE is undefined"
    exit 1
fi

script_dir=$(
    cd "$(dirname "${BASH_SOURCE[0]}")"
    pwd
)
has_vip=$(func_has_vip)

if ! "$script_dir"/keepalivedctl status; then
    "$script_dir"/keepalivedctl start
fi

func_has_vip() {
    local ip_list
    ip_list=$(hostname -I | sed 's/ /\n/g' | grep -v '^$')
    if [ "$ip_list" ]; then
        for ip in $ip_list; do
            if [ "$ip" -eq "$HARBOR_VIP" ]; then
                echo "Y"
                return
            fi
        done
    fi
    echo "N"
}

while true; do
    if [ "$has_vip" == "Y" ] && [ "$(func_has_vip)" == "N" ]; then
        echo "vip gone"
        has_vip="N"
        "$script_dir"/harborctl stop
    fi
    if [ "$has_vip" == "N" ] && [ "$(func_has_vip)" == "Y" ]; then
        echo "vip coming"
        has_vip="Y"
        "$script_dir"/harborctl start
    fi
    sleep 1
done
