#!/bin/sh

if [ -z "$CEPH_POOL_NAME" ]; then
    echo "env CEPH_POOL_NAME is undefined"
    exit 1
fi
if [ -z "$CEPH_IMAGE_NAME" ]; then
    echo "env CEPH_IMAGE_NAME is undefined"
    exit 1
fi
if [ -z "$CEPH_MON_HOST" ]; then
    echo "env CEPH_MON_HOST is undefined"
    exit 1
fi
if [ -z "$CEPH_USER" ]; then
    echo "env CEPH_USER is undefined"
    exit 1
fi
if [ -z "$CEPH_USER_KEY" ]; then
    echo "env CEPH_USER_KEY is undefined"
    exit 1
fi
if [ -n "$KEEPALIVED_VIP" ]; then
    echo "env KEEPALIVED_VIP not defined"
    exit 1
fi
if [ -n "$KEEPALIVED_ROLE" ]; then
    echo "env KEEPALIVED_ROLE not defined"
    exit 1
fi

exec /usr/bin/runsvdir -P /etc/service
