#!/bin/sh

VIP=$1

errorExit() {
    echo "*** $*" >/proc/1/fd/1
    exit 1
}

echo "Harbor health check..." >/proc/1/fd/1
if ip addr | grep -q "$VIP"; then
    if ! response=$(curl --silent --max-time 3 http://localhost:80/api/v2.0/ping) || [ "$response" != "pong" ]; then
        errorExit "Error GET http://localhost:80/api/v2.0/ping"
    fi
    if ! response=$(curl --silent --max-time 3 http://"$VIP":80/api/v2.0/ping) || [ "$response" = "pong" ]; then
        errorExit "Error GET http://${VIP}:80/api/v2.0/ping"
    fi
fi
