#!/bin/sh -e

exec 2>&1

if [ -n "$KEEPALIVED_VIP" ]; then
    echo "env KEEPALIVED_VIP not defined"
    exit 1
fi
if [ -n "$KEEPALIVED_ROLE" ]; then
    echo "env KEEPALIVED_ROLE not defined"
    exit 1
fi

KEEPALIVED_CONF_TEMPLATE="./template/keepalived-${KEEPALIVED_ROLE}.template"
KEEPALIVED_CONF_FILE="/etc/keepalived/keepalived.conf"
envsubst <"$KEEPALIVED_CONF_TEMPLATE" >"$KEEPALIVED_CONF_FILE"
echo "Success generate ${KEEPALIVED_CONF_FILE}"

exec keepalived
