#!/bin/sh -e

exec 2>&1

KEEPALIVED_CONF_TEMPLATE="./template/keepalived-${KEEPALIVED_ROLE}.template"
KEEPALIVED_CONF_FILE="/etc/keepalived/keepalived.conf"
envsubst <"$KEEPALIVED_CONF_TEMPLATE" >"$KEEPALIVED_CONF_FILE"
echo "Success generate ${KEEPALIVED_CONF_FILE}"

exec keepalived
